### PR TITLE
Front End Design

### PR DESCRIPTION
**Pull request by WormJim**
I've implemented some front end design work.  

Pull this down and run both npm run build, and in a separate terminal, npm run serve to see how things look.

There are still things needed to be configured, such as link, but for the most part, the design in similar to the intended project.

### CODE REVIEW

**Comment by CodeWritingCow** [comment]
Hey @WormJim: The server isn't connecting to any database. (See screenshot below.) I see that your repo's `.gitignore` includes `db` files, which is fine. However, if the repo doesn't have a database file, does your app create a database and seed it with mock data?

screen shot 2019-02-16 at 8 10 14 pm

Also, not much appeared in the browser. Perhaps it's because the server couldn't connect to a database.

This is how the page looks on load:
screen shot 2019-02-16 at 8 09 23 pm

After I click the `pizza` link:
screen shot 2019-02-16 at 8 08 43 pm

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
Hey @WormJim: The server isn't connecting to any database. (See screenshot below.) I see that your repo's `.gitignore` includes `db` files, which is fine.

However, if the repo lacks a database file, can your app detect that? Then create a new database file and seed it with mock data? If that functionality exists in your code base, you might want to test it again. If it doesn't, you might want to add it.

screen shot 2019-02-16 at 8 10 14 pm

Also, not much appeared in the browser. Perhaps it's because the server couldn't connect to a database.

This is how the page looks on load:
screen shot 2019-02-16 at 8 09 23 pm

After I click the `pizza` link:
screen shot 2019-02-16 at 8 08 43 pm

**Comment by WormJim** [comment]
Hmm, interesting.  I would suggest for now to open up postman and run localhost:3014/api/seed/populate/db/true as a PATCH Request to fill the DB.  

I will look into this and see what I can do.  The reason I ignored the file is because every time I seeded the DB I would have a conflict on other branches.  The db file always changed regardless of the branch I was in.  

For now, check the above out

**Comment by CodeWritingCow** [comment]
When I send a PATCH request to `localhost:3014/api/seed/populate/db/true` via Postman, the server hangs and doesn't respond.

Here's a screenshot from Postman:
screen shot 2019-02-17 at 4 49 26 pm

An error handler in your DB seeding script may be causing the hang-up. See code below: 
https://github.com/motunui/grahn-service/blob/16d1d047306ceacb02a3631c9667738db047e36e/server/api/routes/_seed/index.js#L21-L23
While the error is stored in the variable `blah`, the server never sends `blah` back to the client. Perhaps you should rewrite the error handler, so it does send an error message to the client.

**Comment by WormJim** [comment]
Gary,

I will be working on the ignore file now, but if you get to this before I finish that, do the below.

I've made some changes.  The DB file still needs to be seeded and it's containing folder needs to be created. I plan on re configuring the ignore file, but for now you'll have to manually create the folder and seed the DB.  

The containing folder should be placed in server/.db/{leave this folder blank}.  Than seed the db by running that PATCH request.  

The reason it is failing is because the .db folder is missing, and the program doesn't know where to put the db file.  The blah variable doesn't do anything.  It was just filler.

Once the server is running, and the DB file is created, in another terminal run npm run build.  You should be able to see the work.

**Comment by CodeWritingCow** [comment]
OK, I added `server/.db`. Now the app is showing images and other event info.

Style the component with CSS to make it look like Trip Advisor, and it's good to go.

Screenshot of what I see:
screen shot 2019-02-17 at 6 16 03 pm

**Comment by WormJim** [comment]
Yes, you will need to repull the code.   You'll see the styling. The pull you are working from is older.

**Comment by CodeWritingCow** [comment]
Repulled the code, but now the browser is showing nothing. There is no error message in my VS Code terminal or the browser console. I'll try your app again on Monday.

**Comment by WormJim** [comment]
Sorry, I forgot to tell you. This works based on the id you provide in the URL bar. A blank path will show nothing.  You'll need to supply an id.  so `localhost:3014/${event 1 through 198}`.  You can choose any id you'd like.

**Comment by CodeWritingCow** [comment]
I see it now. It looks beautiful. It even has the "low price guarantee" modal. Just like the real thing!

There is a minor difference. Trip Advisor's bookmark icon has a black border with inner white space. Your icon is solid black.

Everything else looks like TA, down to the color scheme.

**Comment by WormJim** [comment]
Yeah, well the bookmark icon is from font awesome and to get the non filled one i'd have to pay. Sooo... that's not happening

**Pull request merged**
