### PR TITLE
Restructured Events Controller and Updated Model Configuration

### PR DESCRIPTION
**Pull request by WormJim**
There were some errors in the Database Schema.  Highlights was not being populated. The Seed file had to be reconfigured to incorporate the proper data into the table.  

Additionally, The controller file had to reconfigured in order to incorporate the proper response of the DB data.

### CODE REVIEW

**Comment by WormJim** [comment]
Added a request which handles a call to the database for a single event.  This seems to work perfectly.

**Comment by CodeWritingCow** [comment]
Hey @WormJim:

In `server/api/routes/event.routes.js`, there is a POST route at `'/'`. Is that your API's root route?

Also, what information are supposed to be posted by the client at that endpoint?

**Comment by WormJim** [comment]
> Hey @WormJim:
> 
> In `server/api/routes/event.routes.js`, there is a POST route at `'/'`. Is that your API's root route?
> 
> Also, what information are supposed to be posted by the client at that endpoint?

Hey @CodeWritingCow,

That POST was just some testing I was doing. There really shouldn't be any POSTing, PUTing or DELETEing in the application.  The only time that would happen, I presume, would be in an admin page where the admin can manage the data.  I was just playing around when writing this.

It will  most probably be removed

**Comment by WormJim** [comment]
@CodeWritingCow 

If you approve the commits, please mark them as accepted.  If you think I should change something, please mark them as change requested.  That way there is no ambiguity as to what you suggest I do.  It will give me a clear angle as to whether I should merge the PR.

**Review by CodeWritingCow — APPROVED** [review]
Looks fine. The POST route was the only thing that caught my eyes.

**Pull request merged**
