### PR TITLE
Database Set Up

### PR DESCRIPTION
**Pull request by WormJim**

### CODE REVIEW

**Comment by WormJim** [comment]
@CodeWritingCow  Please Review

**Comment by WormJim** [comment]
@FinTechfullstack

**Comment by FinTechfullstack** [comment]
I would suggest using destructuring in module.exports. Good enough for government work first commit.

**Comment by CodeWritingCow** [comment]
In database/seed.js, you're generating your fake data in a for-loop. The loop generates prices by multiplying each index by 100.

How about randomizing the price instead? Perhaps you can use methods such as Math.random().

**Pull request merged**
