### PR TITLE
Seed Merge

### PR DESCRIPTION
**Pull request by WormJim**
The Sever API calls were restructured to handle closure and pass the db around to each request. 

Additionally, a seed route was added in order to handle a request to repopulate the database.  
Example: PATCH:/api/seed/populate/db/true

There were some old files which were not needed anymore, they have been removed

### CODE REVIEW

**Review by CodeWritingCow — CHANGES_REQUESTED** [review]
Hi @WormJim:

Can you rename the parameters `mod` and `mods`? The names are vague; I don't understand what they represent.

**Comment by WormJim** [comment]
Hey @CodeWritingCow ,

I renamed the variables.  You can check them out in the commit above.

Also, it was a bit hard to find the file you were talking about.  I had to search around in order to find where you were referencing `mod `and `mods`. 

It is possible to leave a comment directly on the code block you are trying to reference, or directly in the file you are referring to.  Please explore this. that way I will know what you mean, where to go and what to look for. When looking at the code, you will notice a plus sign on the left of the line.  Clicking this will provide a comment block ability. 

Let me know if this works for you, so I can merge the Pull.

**Review by CodeWritingCow — APPROVED** [review]
Looks good. The meaning of the variable names is clear now.

**Comment by CodeWritingCow** [comment]
OK I see the plus sign now. Good suggestion. Thanks!

**Pull request merged**
